version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on: 
      - db
    ports: 
      - 8080:8080
    environment:
      DATABASE_URL: postgres://unicorn_user:magical_password@db:5432/rainbow_database
    networks: 
      - app-network

  db:
    image: postgres:10
    env_file: ./database.env
    ports: 
      - 5432:5432
    volumes:
      - ./database-data:/var/lib/postgresql/data/
    networks: 
      - app-network

networks:
  app-network:
    driver: bridge
  
  